### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by mfaughn** [metanorma/metanorma-tutorial#3]
The link to the Metanormal Tutorial points here: https://www.metanorma.org/tutorial/tutorial_start

The link results in a 404 error.

**Comment by ronaldtse** [comment]
Thank you @mfaughn for discovering the broken link. This repository is actually obsolete, so please refer to the latest documentation on www.metanorma.org. Feel free to raise any issues in other active GitHub repositories to contact our team directly if any assistance is needed. Thanks!
